DROP TABLE IF EXISTS feeds;
DROP TABLE IF EXISTS ads;

CREATE TABLE ads (
    log_id INT UNSIGNED NOT NULL,
    label TINYINT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    gender TINYINT UNSIGNED NOT NULL,
    residence TINYINT UNSIGNED NOT NULL,
    city SMALLINT UNSIGNED NOT NULL,
    city_rank TINYINT UNSIGNED NOT NULL,
    series_dev TINYINT UNSIGNED NOT NULL,
    series_group TINYINT UNSIGNED NOT NULL,
    emui_dev TINYINT UNSIGNED NOT NULL,
    device_name SMALLINT UNSIGNED NOT NULL,
    device_size SMALLINT UNSIGNED NOT NULL,
    net_type TINYINT UNSIGNED NOT NULL,
    task_id SMALLINT UNSIGNED NOT NULL,
    adv_id SMALLINT UNSIGNED NOT NULL,
    creat_type_cd TINYINT UNSIGNED NOT NULL,
    adv_prim_id SMALLINT UNSIGNED NOT NULL,
    inter_type_cd TINYINT UNSIGNED NOT NULL,
    slot_id TINYINT UNSIGNED NOT NULL,
    site_id TINYINT UNSIGNED NOT NULL DEFAULT 1,
    spread_app_id SMALLINT UNSIGNED NOT NULL,
    hispace_app_tags TINYINT UNSIGNED NOT NULL,
    app_second_class TINYINT UNSIGNED NOT NULL,
    app_score DECIMAL(3,1) NOT NULL,
    ad_click_list_v001 JSON NOT NULL,
    ad_click_list_v002 JSON NOT NULL,
    ad_click_list_v003 JSON NOT NULL,
    ad_close_list_v001 JSON NOT NULL,
    ad_close_list_v002 JSON NOT NULL,
    ad_close_list_v003 JSON NOT NULL,
    pt_d BIGINT UNSIGNED NOT NULL,
    u_newsCatInterestsST JSON NOT NULL,
    u_refreshTimes TINYINT UNSIGNED NOT NULL,
    u_feedLifeCycle TINYINT UNSIGNED NOT NULL,
    INDEX idx_log_id (log_id),
    INDEX idx_user_id (user_id),
    INDEX idx_label (label),
    INDEX idx_pt_d (pt_d)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE feeds (
    u_userId INT UNSIGNED NOT NULL,
    u_phonePrice TINYINT UNSIGNED NOT NULL,
    u_browserLifeCycle TINYINT UNSIGNED NOT NULL,
    u_browserMode TINYINT UNSIGNED NOT NULL,
    u_feedLifeCycle TINYINT UNSIGNED NOT NULL,
    u_refreshTimes TINYINT UNSIGNED NOT NULL,
    u_newsCatInterests JSON NOT NULL,
    u_newsCatDislike JSON NOT NULL,
    u_newsCatInterestsST JSON NOT NULL,
    u_click_ca2_news JSON NOT NULL,
    i_docId VARCHAR(40) NOT NULL,
    i_s_sourceId VARCHAR(40) NOT NULL,
    i_regionEntity SMALLINT UNSIGNED NOT NULL,
    i_cat TINYINT UNSIGNED NOT NULL,
    i_entities JSON NOT NULL,
    i_dislikeTimes TINYINT UNSIGNED NOT NULL,
    i_upTimes TINYINT UNSIGNED NOT NULL,
    i_dtype TINYINT UNSIGNED NOT NULL,
    e_ch TINYINT UNSIGNED NOT NULL,
    e_m SMALLINT UNSIGNED NOT NULL,
    e_po TINYINT UNSIGNED NOT NULL,
    e_pl SMALLINT UNSIGNED NOT NULL,
    e_rn TINYINT UNSIGNED NOT NULL,
    e_section TINYINT UNSIGNED NOT NULL,
    e_et BIGINT UNSIGNED NOT NULL,
    label TINYINT NOT NULL,
    cillabel TINYINT NOT NULL,
    pro TINYINT UNSIGNED NOT NULL,
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id),
    INDEX idx_u_userId (u_userId),
    INDEX idx_label (label),
    INDEX idx_cillabel (cillabel),
    INDEX idx_e_et (e_et),
    INDEX idx_i_docId (i_docId),
    INDEX idx_user_timestamp (u_userId, e_et)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE OR REPLACE VIEW ads_feeds_joined AS
SELECT 
    a.log_id,
    a.label AS ads_label,
    a.user_id,
    a.age,
    a.gender,
    a.residence,
    a.city,
    a.pt_d AS ad_timestamp,
    f.id AS feed_id,
    f.u_userId,
    f.label AS feed_label,
    f.cillabel,
    f.pro,
    f.e_et AS feed_timestamp,
    f.i_docId,
    f.i_cat
FROM ads a
LEFT JOIN feeds f ON a.user_id = f.u_userId;



DROP TABLE IF EXISTS synthetic_train_smote;
DROP TABLE IF EXISTS synthetic_train_adasyn;

CREATE TABLE synthetic_train_smote (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    age TINYINT UNSIGNED NOT NULL,  
    gender TINYINT UNSIGNED NOT NULL,  
    residence TINYINT UNSIGNED NOT NULL,  
    city SMALLINT UNSIGNED NOT NULL,  
    city_rank TINYINT UNSIGNED NOT NULL, 
    series_dev TINYINT UNSIGNED NOT NULL,  
    series_group TINYINT UNSIGNED NOT NULL,  
    emui_dev TINYINT UNSIGNED NOT NULL,  
    device_name TINYINT UNSIGNED NOT NULL,  
    device_size SMALLINT UNSIGNED NOT NULL,  
    net_type TINYINT UNSIGNED NOT NULL,  
    task_id SMALLINT UNSIGNED NOT NULL,  
    adv_id SMALLINT UNSIGNED NOT NULL,  
    creat_type_cd TINYINT UNSIGNED NOT NULL,  
    adv_prim_id SMALLINT UNSIGNED NOT NULL,  
    inter_type_cd TINYINT UNSIGNED NOT NULL,  
    slot_id TINYINT UNSIGNED NOT NULL,  
    site_id TINYINT UNSIGNED NOT NULL,  
    spread_app_id TINYINT UNSIGNED NOT NULL,  
    hispace_app_tags TINYINT UNSIGNED NOT NULL,  
    app_second_class TINYINT UNSIGNED NOT NULL,  
    app_score DECIMAL(10,2) NOT NULL,
    u_refreshTimes DECIMAL(10,2) NOT NULL,
    u_feedLifeCycle DECIMAL(10,2) NOT NULL,
    hour TINYINT NOT NULL DEFAULT -1,
    dayofweek TINYINT NOT NULL DEFAULT -1,
    feeds_u_phonePrice DECIMAL(10,2) NOT NULL,  
    feeds_u_browserLifeCycle DECIMAL(10,2) NOT NULL,  
    feeds_u_browserMode DECIMAL(10,2) NOT NULL,  
    feeds_u_feedLifeCycle DECIMAL(10,2) NOT NULL,  
    feeds_u_refreshTimes DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatInterests DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatDislike DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatInterestsST DECIMAL(10,2) NOT NULL,  
    feeds_u_click_ca2_news DECIMAL(10,2) NOT NULL,  
    feeds_label DECIMAL(10,2) NOT NULL,
    label TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_user_id (user_id),
    INDEX idx_label (label),
    INDEX idx_user_label (user_id, label),
    INDEX idx_task_id (task_id),
    INDEX idx_adv_id (adv_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='SMOTE synthetic training data - 482,668 rows, balanced 50/50 label distribution';

CREATE TABLE synthetic_train_adasyn (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    age TINYINT UNSIGNED NOT NULL,  
    gender TINYINT UNSIGNED NOT NULL,  
    residence TINYINT UNSIGNED NOT NULL,  
    city SMALLINT UNSIGNED NOT NULL,  
    city_rank TINYINT UNSIGNED NOT NULL, 
    series_dev TINYINT UNSIGNED NOT NULL,  
    series_group TINYINT UNSIGNED NOT NULL,  
    emui_dev TINYINT UNSIGNED NOT NULL,  
    device_name TINYINT UNSIGNED NOT NULL,  
    device_size SMALLINT UNSIGNED NOT NULL,  
    net_type TINYINT UNSIGNED NOT NULL,  
    task_id SMALLINT UNSIGNED NOT NULL,  
    adv_id SMALLINT UNSIGNED NOT NULL,  
    creat_type_cd TINYINT UNSIGNED NOT NULL,  
    adv_prim_id SMALLINT UNSIGNED NOT NULL,  
    inter_type_cd TINYINT UNSIGNED NOT NULL,  
    slot_id TINYINT UNSIGNED NOT NULL,  
    site_id TINYINT UNSIGNED NOT NULL,  
    spread_app_id TINYINT UNSIGNED NOT NULL,  
    hispace_app_tags TINYINT UNSIGNED NOT NULL,  
    app_second_class TINYINT UNSIGNED NOT NULL,  
    app_score DECIMAL(10,2) NOT NULL,
    u_refreshTimes DECIMAL(10,2) NOT NULL,
    u_feedLifeCycle DECIMAL(10,2) NOT NULL,
    hour TINYINT NOT NULL DEFAULT -1,
    dayofweek TINYINT NOT NULL DEFAULT -1,
    feeds_u_phonePrice DECIMAL(10,2) NOT NULL,  
    feeds_u_browserLifeCycle DECIMAL(10,2) NOT NULL,  
    feeds_u_browserMode DECIMAL(10,2) NOT NULL,  
    feeds_u_feedLifeCycle DECIMAL(10,2) NOT NULL,  
    feeds_u_refreshTimes DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatInterests DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatDislike DECIMAL(10,2) NOT NULL,  
    feeds_u_newsCatInterestsST DECIMAL(10,2) NOT NULL,  
    feeds_u_click_ca2_news DECIMAL(10,2) NOT NULL,  
    feeds_label DECIMAL(10,2) NOT NULL,
    label TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_user_id (user_id),
    INDEX idx_label (label),
    INDEX idx_user_label (user_id, label),
    INDEX idx_task_id (task_id),
    INDEX idx_adv_id (adv_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='ADASYN synthetic training data - 482,815 rows, near-balanced 50/50 label distribution';